/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast-1",
  aws_appsync_graphqlEndpoint:
    "https://dkksty3eh5bu3mgup3mka2raue.appsync-api.ap-southeast-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-southeast-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-wyfhzmra6rgurl23jfy6f7g46y",
  userPoolId: "ap-southeast-1_OZPfzOlVh",
  userPoolWebClientId: "4egqhlo0dn4rsocpk082df9339",
  mandatorySignIn: true,
  authenticationFlowType: "USER_PASSWORD_AUTH",
  oauth: {
    domain: "https://naascogni.auth.ap-southeast-1.amazoncognito.com",
    scope: ["email", "profile", "openid"],
    // redirectSignIn: process.env.NEXT_PUBLIC_AWS_OAUTH_REDIRECT_SIGN_IN,
    // redirectSignOut: process.env.NEXT_PUBLIC_AWS_OAUTH_REDIRECT_SIGN_OUT,
    responseType: "token", // or 'token', note that REFRESH token will only be generated when the responseType is code
  },
};

export default awsmobile;
